---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acm-policies

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/name: rhacm-policies
    app.kubernetes.io/component: governance
    app.kubernetes.io/part-of: platform-management

resources:
- ManagedClusterSetBinding_default.yaml

generators:
- PolicyGenerator_cluster-management.yaml
- PolicyGenerator_tenant-management.yaml
